BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-orhun-gui"
BBFILE_PATTERN_meta-orhun-gui = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-orhun-gui = "6"

LAYERDEPENDS_meta-orhun-gui = "core"
LAYERSERIES_COMPAT_meta-orhun-gui = "whinlatter"
